# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('emailCode', models.CharField(max_length=40, null=True)),
                ('passwordCode', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_profile', 'View user profile'),),
            },
        ),
    ]
